spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa
    username: postgres
    password: chowntoalidg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update